### ISSUE TITLE
When logging in we need 2FA to validate users to protect the recipients PII so we are compliant with the Privacy act and Security Controls

### ISSUE THREAD

**Issue by willeybryan** [cds-snc/CANotifier#12]
**What?**
- Gov.uk says their login has 2fa, does our fork have that on by default?
- Can we use SMS for 2FA even though it isn't the best option?
- Can it be disabled while we build and test?

**Why?**
- We probably need 2fa if we are going to be storing peoples names, emails, phone numbers, and other person information.

**Comment by willeybryan** [comment]
@damcom333 Do we need 2FA on for this app? if so when would we have to have it turned on?

**Comment by maxneuvians** [comment]
The app already enforces 2fa email links or sms

**Comment by willeybryan** [comment]
Ok so we should just leave it be and use it for our logins to the app while it is being developed?

**Comment by maxneuvians** [comment]
Email and SMS is probably the least secure option - would be nice to demo Yubikey, if if not that then Google 2FA

**Comment by willeybryan** [comment]
On by default with Email for testing.
